name: add label of non_standard Issue

on:
  issues:
    types: [opened, edited]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - id: check-issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          title-includes: '【,BUG,】'
          body-includes: '问题描述,问题复现步骤'
      - name: add-label
        uses: actions-cool/issues-helper@v3
        if: ${{steps.check-issue.outputs.check-result == 'true'}}
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'bug'
