name: Remove non-standard issues

on:
  issues:
    types: [opened, edited] # issue 打开或者编辑后

jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, fromJson('["问题描述", "复现流程"]')) == false
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}